### ISSUE TITLE
Document where the design for `s2v` comes from

### ISSUE THREAD

**Issue by cipriancraciun** [jedisct1/libsodium-deterministic-encryption#1]
Looking at the implementation of `s2v` it resembles the `S2V` construct from [RFC 5297](<https://datatracker.ietf.org/doc/html/rfc5297#section-2.4>).

The only difference I see, besides the choice of hash function and sizes, is that if the message is less than the MAC size, you apply an extra `d[mlen] ^= 0x80;`.

Am I correct?

**Comment by jedisct1** [comment]
S2V is defined in Rogaway's [paper](https://www.iacr.org/archive/eurocrypt2006/40040377/40040377.pdf) -- See fig.2

It's a generic construction, so any PRF can be used. Setting the bit after the data is required to make the distinction between padding bits and zero bits from actual data.

**Comment by jedisct1** [comment]
The construction here is an instantiation of the SIV mode described in that paper. Pretty boring, but in a good way.

S2V is used in the `SIV` mode, but also in [AES-OCB](https://github.com/ziglang/zig/blob/24d8d12caf05e52fe938d1eb01211b2470cffb41/lib/std/crypto/aes_ocb.zig#L31-L37).

It can be used in any other context, to provide domain separation between members of a tuple.
