### ISSUE TITLE
[question]  An alternate simpler `s2v` that just uses `libsodium` primitives

### ISSUE THREAD

**Issue by cipriancraciun** [jedisct1/libsodium-deterministic-encryption#2]
(This is not a bug, but an implementation decision question.  I would have posted this into the GitHub discussions, but that was not enabled at the moment for this repository.)

----

Looking at the implementation `crypto_aead_det_xchacha20_encrypt_detached` (and counterpart) they are quite straight-forward to implement, with the exception of the `s2v` function that generates the actual nonce for XChaCha20.

Please view this in the context of someone that just has access to the standard `libsodium` (or equivalent) library, and would like to implement something similar based on SIVs.  Therefore implementing `s2v`, especially correctly, is far from the reach of most developers, myself included.

Thus, my question is:  couldn't one implement `s2v` by just leveraging the `crypto_generichash_*` family of functions?

----

For example, copy-pasting from [RFC 5297](<https://datatracker.ietf.org/doc/html/rfc5297#section-2.4>) the basic design of that `S2V` (which I'm assuming, as per #1, was the inspiration for the current `s2v` in this repository) is:
~~~~
                  +----+       +----+       +------+      +----+
                  | S1 |       | S2 | . . . | Sn-1 |      | Sn |
                  +----+       +----+       +------+      +----+
     <zero>   K     |            |             |             |
       |      |     |            |             |             V
       V      |     V            V             V    /----> xorend
   +-----+    |  +-----+      +-----+       +-----+ |        |
   | AES-|<----->| AES-|  K-->| AES-|  K--->| AES-| |        |
   | CMAC|       | CMAC|      | CMAC|       | CMAC| |        |
   +-----+       +-----+      +-----+       +-----+ |        V
       |           |             |             |    |     +-----+
       |           |             |             |    | K-->| AES-|
       |           |             |             |    |     | CMAC|
       |           |             |             |    |     +-----+
       \-> dbl -> xor -> dbl -> xor -> dbl -> xor---/        |
                                                             V
                                                           +---+
                                                           | V |
                                                           +---+
~~~~

(Here, the RFC `S2V` accepts zero or more additional data, and the plain text is fed into the last `Sn`.)

Couldn't one replace this schema with the following simpler alternative:
* let `Hn` be the hash (using `crypto_generichash`) each of the `Sn` parts using the same key `K`;  (these values could be then cached in case one of the `Sn`'s are somewhat constant, as the RFC suggests;)
* let `V` (i.e. the MAC/nonce) be the hash (again using `crypto_generichash`) with key `K` of the concatenation of the previous `Hn` hashes;

Alternatively, if one doesn't care about caching partial hashes, wouldn't the hash of a canonical representation of the sequence `Sn` be enough?  (i.e. hash `sizeof(S1) || S1 || sizeof(S2) || S2 || ...`)

My assumption is that the current construction of `S2V` from the RFC uses the "doubling and xor" method because it is far more efficient than just feeding everything back into another `AES-CMAC` (or the `Blake` family in our case).  Or is there another property that I'm missing?

----

I've tried reading (truthfully more skimming through) the original [Deterministic Authenticated-Encryption: A Provable-Security Treatment of the Key-Wrap Problem](<https://eprint.iacr.org/2006/221>) paper that introduced SIVs, which in section 5, "Enriching a PRF to take Vectors of Strings as Input: The S2V Construction", does seem to hint exactly to what I've asserted above;  quoting the paper:

> At first glance it might seem like there’d be little to say about sPRF-to-vPRF conversion: there’s an obvious approach for solving the problem, and it’s obviously correct.
>
> Namely, encode any vector of strings `X = (X1, . . . , Xm )` into a single string `X` and apply the sPRF to that. By encode we mean any reversible, easily-computed map of a vector of strings into a single one, say `X1, . . . , Xm = X1 || N1 || · · · || Xm || Nm` where `Ni = |Xi|64` is the length of `Xi` encoded into 64 bits.
>
> The problem with making a vPRF in such a way is a diminution of efficiency.

(From there on it's hard for me to follow...)

----

I am not a cryptographer, I just want to make sense of all these, thus any feedback is welcome.

Thanks!

**Comment by jedisct1** [comment]
Well, this implementation also only uses libsodium :)

`S2V` can indeed be replaced with length-prefixed tuple members as in [tuplehash](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-185.pdf). 

`S2V` is faster for small inputs, which is typical for associated data.

It also allows applications to just recursively call the function over all the tuple members, instead of having to use a specific encoding.
It can also be seen as a way to discourage a simple concatenation of the members, that would be insecure.

**Comment by jedisct1** [comment]
Also take a look at [daence](https://eprint.iacr.org/2020/067.pdf), that reuses ChaCha20 (or Salsa20) for the PRF.

Should be pretty straightforward to implement on top of libsodium.
